package errcode

var (
	UsernameHasExisted      = NewError(20001, "用户名已存在")
	UsernameLengthLimit     = NewError(20002, "用户名长度3~12")
	UsernameCharLimit       = NewError(20003, "用户名只能包含字母、数字")
	PasswordLengthLimit     = NewError(20004, "密码长度6~16")
	UserRegisterFailed      = NewError(20005, "用户注册失败")
	UserHasBeenBanned       = NewError(20006, "该账户已被封停")
	NoPermission            = NewError(20007, "无权限执行该请求")
	UserHasBindOTP          = NewError(20008, "当前用户已绑定二次验证")
	UserOTPInvalid          = NewError(20009, "二次验证码验证失败")
	UserNoBindOTP           = NewError(20010, "当前用户未绑定二次验证")
	ErrorOldPassword        = NewError(20011, "当前用户密码验证失败")
	ErrorCaptchaPassword    = NewError(20012, "图形验证码验证失败")
	AccountNoPhoneBind      = NewError(20013, "拒绝操作: 账户未绑定手机号")
	TooManyLoginError       = NewError(20014, "登录失败次数过多，请稍后再试")
	GetPhoneCaptchaError    = NewError(20015, "短信验证码获取失败")
	TooManyPhoneCaptchaSend = NewError(20016, "短信验证码获取次数已达今日上限")
	ExistedUserPhone        = NewError(20017, "该手机号已被绑定")
	ErrorPhoneCaptcha       = NewError(20018, "手机验证码不正确")
	MaxPhoneCaptchaUseTimes = NewError(20019, "手机验证码已达最大使用次数")
	NicknameLengthLimit     = NewError(20020, "昵称长度2~12")
	NoExistUsername         = NewError(20021, "用户不存在")
)
